# Generated by Django 4.0.3 on 2022-03-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_autor'),
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Autors',
        ),
    ]
