# Generated by Django 4.0.3 on 2022-03-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_autor'),
        ('autores', '0002_rename_autor_autors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autors',
            new_name='Autor',
        ),
    ]
